TRANSLATIONS = {
    "zh": {
        "app_title": "大学软件工程项目 - ATM柜员机模拟系统",
        "banner_title": "ATM 柜员机模拟系统",
        "banner_subtitle": "安全 · 便捷 · 可靠",
        "account": "账号",
        "password": "密码",
        "login_btn": "登  录",
        "register_btn": "注册新账户",
        "lang_switch": "EN",
        "menu_title": "请选择服务内容",
        "balance_btn": "查 询 余 额",
        "deposit_btn": "存 款 业 务",
        "withdraw_btn": "取 款 业 务",
        "transfer_btn": "转 账 业 务",
        "change_pwd_btn": "修 改 密 码",
        "transactions_btn": "交 易 明 细",
        "logout_btn": "退 出 登 录",
        "balance_title": "账户余额",
        "balance_current": "当前账户余额",
        "back_menu": "返回主菜单",
        "back_login": "返回登录",
        "submit": "提  交",
        "deposit_title": "存款业务",
        "deposit_label": "请输入存款金额:",
        "withdraw_title": "取款业务",
        "withdraw_label": "请输入取款金额 (100的倍数):",
        "transfer_title": "转账业务",
        "target_account": "目标账户",
        "transfer_amount": "转账金额",
        "transfer_confirm": "确认转账",
        "transactions_title": "交易明细记录",
        "col_seq": "序号",
        "col_type": "类型",
        "col_amount": "金额",
        "col_time": "时间",
        "col_balance": "操作后余额",
        "col_target": "对方账户",
        "tx_none": "暂无交易记录",
        "register_title": "注册新账户",
        "register_pwd": "设置密码",
        "register_confirm": "确认密码",
        "register_hint": "密码长度不小于6位，不允许6位完全相同字符",
        "register_btn_text": "注  册",
        "pwd_title": "安全中心 - 修改密码",
        "pwd_old": "当前旧密码",
        "pwd_new": "输入新密码",
        "pwd_confirm": "确认新密码",
        "pwd_change": "确认修改",
        "msg_login_fail": "账号或密码不正确",
        "msg_account_not_exist": "账号不存在",
        "msg_locked": "密码连续错误3次，账户已被锁定5分钟",
        "msg_locked_remaining": "账户已被锁定，请在 {m}分{s}秒 后重试",
        "msg_login_ok": "登录成功",
        "msg_register_ok": "注册成功！您的账号为：{account}，请妥善保管",
        "msg_deposit_ok": "存款成功，当前余额: {balance}元",
        "msg_deposit_err": "存款金额必须大于0",
        "msg_withdraw_mod": "取款金额必须是100的倍数",
        "msg_withdraw_limit": "单次取款不能超过5000元",
        "msg_withdraw_overdraft": "余额不足，不可透支",
        "msg_withdraw_ok": "取款成功，当前余额: {balance}元",
        "msg_withdraw_invalid": "金额无效",
        "msg_transfer_ok": "转账成功！向账户 {target} 转出 {amount}元，当前余额: {balance}元",
        "msg_transfer_self": "不能转账给自己",
        "msg_transfer_no_target": "目标账户不存在",
        "msg_transfer_positive": "转账金额必须大于0",
        "msg_transfer_overdraft": "余额不足，不可透支",
        "msg_pwd_old_wrong": "旧密码输入错误",
        "msg_pwd_mismatch": "两次输入的新密码不一致",
        "msg_pwd_short": "新密码长度至少需要6位",
        "msg_pwd_same_chars": "新密码不能是完全相同的字符",
        "msg_pwd_ok": "密码修改成功，请重新登录",
        "msg_pwd_length": "密码长度至少需要6位",
        "msg_number_invalid": "请输入有效的数字金额",
        "tx_deposit": "存款",
        "tx_withdraw": "取款",
        "tx_transfer_out": "转出",
        "tx_transfer_in": "转入",
        "msg_error": "错误",
        "msg_success": "成功",
        "remaining_attempts": "剩余尝试次数: {n}",
    },
    "en": {
        "app_title": "ATM Simulator - Software Engineering Project",
        "banner_title": "ATM Simulator System",
        "banner_subtitle": "Secure · Convenient · Reliable",
        "account": "Account",
        "password": "Password",
        "login_btn": "Login",
        "register_btn": "Register",
        "lang_switch": "中文",
        "menu_title": "Please Select a Service",
        "balance_btn": "Balance Inquiry",
        "deposit_btn": "Deposit",
        "withdraw_btn": "Withdraw",
        "transfer_btn": "Transfer",
        "change_pwd_btn": "Change Password",
        "transactions_btn": "Transactions",
        "logout_btn": "Logout",
        "balance_title": "Account Balance",
        "balance_current": "Current Balance",
        "back_menu": "Back to Menu",
        "back_login": "Back to Login",
        "submit": "Submit",
        "deposit_title": "Deposit",
        "deposit_label": "Enter deposit amount:",
        "withdraw_title": "Withdraw",
        "withdraw_label": "Enter withdraw amount (multiples of 100):",
        "transfer_title": "Transfer",
        "target_account": "Target Account",
        "transfer_amount": "Transfer Amount",
        "transfer_confirm": "Confirm Transfer",
        "transactions_title": "Transaction History",
        "col_seq": "No.",
        "col_type": "Type",
        "col_amount": "Amount",
        "col_time": "Time",
        "col_balance": "Balance After",
        "col_target": "Target",
        "tx_none": "No transactions",
        "register_title": "Register New Account",
        "register_pwd": "Set Password",
        "register_confirm": "Confirm Password",
        "register_hint": "Min 6 characters, not all same characters",
        "register_btn_text": "Register",
        "pwd_title": "Security - Change Password",
        "pwd_old": "Current Password",
        "pwd_new": "New Password",
        "pwd_confirm": "Confirm Password",
        "pwd_change": "Confirm Change",
        "msg_login_fail": "Incorrect account or password",
        "msg_account_not_exist": "Account does not exist",
        "msg_locked": "Account locked for 5 minutes after 3 failed attempts",
        "msg_locked_remaining": "Account locked, retry in {m}m {s}s",
        "msg_login_ok": "Login successful",
        "msg_register_ok": "Registration successful! Your account: {account}, keep it safe",
        "msg_deposit_ok": "Deposit successful, balance: {balance} CNY",
        "msg_deposit_err": "Deposit amount must be greater than 0",
        "msg_withdraw_mod": "Amount must be a multiple of 100",
        "msg_withdraw_limit": "Single withdrawal cannot exceed 5000 CNY",
        "msg_withdraw_overdraft": "Insufficient balance, overdraft not allowed",
        "msg_withdraw_ok": "Withdrawal successful, balance: {balance} CNY",
        "msg_withdraw_invalid": "Invalid amount",
        "msg_transfer_ok": "Transfer successful! {amount} CNY to {target}, balance: {balance} CNY",
        "msg_transfer_self": "Cannot transfer to yourself",
        "msg_transfer_no_target": "Target account does not exist",
        "msg_transfer_positive": "Transfer amount must be greater than 0",
        "msg_transfer_overdraft": "Insufficient balance, overdraft not allowed",
        "msg_pwd_old_wrong": "Incorrect old password",
        "msg_pwd_mismatch": "New passwords do not match",
        "msg_pwd_short": "Password must be at least 6 characters",
        "msg_pwd_same_chars": "Password cannot be all the same character",
        "msg_pwd_ok": "Password changed successfully, please login again",
        "msg_pwd_length": "Password must be at least 6 characters",
        "msg_number_invalid": "Please enter a valid number",
        "tx_deposit": "Deposit",
        "tx_withdraw": "Withdrawal",
        "tx_transfer_out": "Transfer Out",
        "tx_transfer_in": "Transfer In",
        "msg_error": "Error",
        "msg_success": "Success",
        "remaining_attempts": "Remaining attempts: {n}",
    }
}
